<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>HelloWorld.FormsApp</AssemblyName>
    <RootNamespace>HelloWorld.FormsApp</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\HelloWorld.FormsApp\**\*.cs" Exclude="..\HelloWorld.FormsApp\bin\**\*;..\HelloWorld.FormsApp\obj\**\*" />
    <EmbeddedResource Include="..\HelloWorld.FormsApp\**\*.resx" Exclude="..\HelloWorld.FormsApp\bin\**\*;..\HelloWorld.FormsApp\obj\**\*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="3.4.0" />
    <PackageReference Include="protobuf-net" Version="3.4.21" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HelloWorld.ConsoleApp\HelloWorld.ConsoleApp.csproj">
      <Private>true</Private>
    </ProjectReference>
    <ProjectReference Include="..\HelloWorld.Library2\HelloWorld.Library2.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="TextFile1.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>